"""
Topic bank for the auto-blog scheduler. Curated list of evergreen + seasonal
themes for Addrika's brand voice (premium incense, low-smoke, mindful living).
The orchestrator alternates between this static bank and trend-driven cycles
(see `auto_blog.py`).
"""

# Each entry: (title_seed, category, geo_city_or_None, suggested_keywords)
TOPIC_BANK = [
    ("The 5 incense rituals that quietly change your morning", "rituals", None,
     ["morning ritual", "natural agarbatti", "low smoke incense", "premium dhoop"]),
    ("Why charcoal-free agarbatti matters for indoor air quality", "wellness", None,
     ["zero charcoal", "indoor air quality", "natural incense India"]),
    ("Vastu fragrances: which incense to burn in which room", "vastu", None,
     ["vastu incense", "fragrance for home", "agarbatti for puja"]),
    ("Kesar Chandan: the centuries-old saffron-sandalwood blend, decoded", "ingredients", None,
     ["kesar chandan agarbatti", "saffron incense", "sandalwood agarbatti"]),
    ("Bilvapatra in your daily puja — meaning, method, and the perfect dhoop", "rituals", None,
     ["bilvapatra puja", "shiva incense", "bilva agarbatti"]),
    ("Nag Champa vs Mogra vs Royal Kewda — which one is right for you?", "compare", None,
     ["nag champa", "mogra agarbatti", "royal kewda incense"]),
    ("Diwali fragrance guide: lighting incense the way your nani did", "festival", None,
     ["diwali agarbatti", "diwali puja", "festival incense"]),
    ("Bambooless dhoop: why the world is moving away from the bamboo stick", "innovation", None,
     ["bambooless dhoop", "8 inch dhoop", "natural dhoop"]),
    ("The science of low-smoke incense — and why it actually matters", "wellness", None,
     ["low smoke incense", "lung-friendly agarbatti", "clean burn"]),
    ("Aromatherapy for stress: the 4 incense scents backed by Ayurveda", "wellness", None,
     ["aromatherapy India", "ayurvedic incense", "stress relief fragrance"]),
    ("How to choose B2B-grade agarbatti for your store: a buyer's guide", "b2b", None,
     ["b2b agarbatti", "wholesale incense India", "premium agarbatti supplier"]),
    ("The Addrika promise: hand-rolled, charcoal-free, made in Delhi", "brand", "Delhi",
     ["addrika incense", "delhi agarbatti supplier", "premium hand rolled incense"]),
    ("Mumbai shopkeepers' favourite incense: the SKUs that always sell", "b2b", "Mumbai",
     ["mumbai agarbatti supplier", "incense bestseller", "wholesale fragrance Mumbai"]),
    ("Chandigarh wellness studios are switching to charcoal-free — here's why", "b2b", "Chandigarh",
     ["chandigarh incense", "wellness studio agarbatti", "yoga studio incense"]),
    ("Bangalore yoga teachers on the only incense they recommend", "wellness", "Bangalore",
     ["bangalore yoga incense", "studio agarbatti", "meditation incense"]),
    ("Pune housewives swear by these 3 daily-use agarbatti scents", "lifestyle", "Pune",
     ["pune agarbatti", "daily use incense", "home fragrance India"]),
    ("Hyderabad temples and the dhoop that lasts the entire aarti", "rituals", "Hyderabad",
     ["hyderabad temple incense", "long-burning dhoop", "aarti agarbatti"]),
    ("Lucknow's attar tradition meets the modern agarbatti", "heritage", "Lucknow",
     ["lucknow attar incense", "traditional agarbatti", "ittar fragrance"]),
    ("Gift a fragrance, gift an experience: incense as a thoughtful gift", "lifestyle", None,
     ["incense gift India", "premium agarbatti gift box", "festival gift"]),
    ("How to read an agarbatti label like a sommelier reads wine", "education", None,
     ["agarbatti ingredients", "natural incense label", "incense quality"]),
    ("Holi, Eid, Christmas — incense for India's most loved festivals", "festival", None,
     ["festival incense India", "holi agarbatti", "religious fragrance"]),
    ("The 7-day fragrance reset: incense routine for sleep, focus, calm", "wellness", None,
     ["incense for sleep", "focus fragrance", "calming agarbatti"]),
    ("From the rolling room: how Addrika makes a single Bilvapatra stick", "behind-scenes", None,
     ["how agarbatti is made", "addrika manufacturing", "hand rolled incense"]),
    ("Why your incense smells different in monsoon (and what to do)", "seasonal", None,
     ["monsoon incense", "incense storage", "humidity agarbatti"]),
    ("The case for wholesale: 5 reasons retailers love B2B incense supply", "b2b", None,
     ["b2b wholesale incense", "retailer supply", "agarbatti reseller"]),
    ("Beyond puja: incense as decor, mood-setter, and personal scent", "lifestyle", None,
     ["incense as decor", "modern incense use", "home ambience"]),
    ("Karva Chauth, Navratri, Janmashtami: the right incense for vrat days", "festival", None,
     ["vrat incense", "navratri agarbatti", "religious occasions"]),
    ("Sandalwood, jasmine, rose: the 3 incense families every Indian home should know", "education", None,
     ["sandalwood agarbatti", "jasmine incense", "rose dhoop"]),
    ("How to scale a small incense business: lessons from a B2B sourcing partner", "b2b", None,
     ["agarbatti business", "wholesale incense supplier", "incense reseller India"]),
    ("Eco-friendly fragrance: the future of charcoal-free, plastic-free incense", "sustainability", None,
     ["eco friendly incense", "sustainable agarbatti", "plastic free packaging"]),
]


# Indian festival / season → topic hint by month. Used in trend-driven cycles.
SEASONAL_HINTS = {
    1:  "winter wellness, Lohri, Pongal, Sankranti — warming incense, sesame ritual",
    2:  "Maha Shivratri prep, Vasant Panchami — Bilvapatra, Shiva, yellow flowers",
    3:  "Holi, color season, end of winter — celebration, festive incense",
    4:  "Ram Navami, Hanuman Jayanti, Baisakhi — temple fragrances, devotional",
    5:  "Akshaya Tritiya, summer onset, Buddha Purnima — cooling, prosperity",
    6:  "monsoon onset, Ganga Dussehra — earthy, calming, humidity tips",
    7:  "Sawan, Guru Purnima, monsoon — Shiva worship, Bilvapatra peak",
    8:  "Raksha Bandhan, Janmashtami, Independence — sibling gift, Krishna",
    9:  "Ganesh Chaturthi, Onam, Pitru Paksha — Ganesha, prosperity",
    10: "Navratri, Dussehra, Karva Chauth — feminine devotion, marital prosperity",
    11: "Diwali, Bhai Dooj, Chhath, Tulsi Vivah — peak festive season",
    12: "Christmas, Gita Jayanti, year-end reflection — gifting, calm",
}
